config/routes.rb
Rails.application.routes.draw do
  resources :available_time_slots
  resources :tracks
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/available_time_slot.rb
class AvailableTimeSlot < ApplicationRecord
  has_and_belongs_to_many :tracks
end

app/models/track.rb
class Track < ApplicationRecord
  has_many :available_time_slots
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/available_time_slots_controller.rb
class AvailableTimeSlotsController < InheritedResources::Base
  def index
    @timeslots = AvailableTimeSlot.all
  end

  def new
  end

  def create
    @timeslot = AvailableTimeSlot.new(timeslot_params)
      if @timeslot.save
        redirect_to available_time_slots_path(@timeslot)
      else
        render 'index'
      end
  end

    def show
      @timeslot = AvailableTimeSlot.find(params[:id])
    end

    private

    def timeslot_params
      params.require(:available_time_slots).permit(:hour, :track_id)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @timeslots = AvailableTimeSlot.all
    @tracks = Track.all
    @city_options = Track.all.map { |c| [c.city, c.id] }
    @tracks = Track.where(id: params[:city])
  end

  def new
  end

  def create
    @timeslot = AvailableTimeSlot.new(timeslot_params)
      if @timeslot.save
        redirect_to available_time_slots_path(@timeslot)
      else
        render 'index'
      end
  end

    def show
      @timeslot = AvailableTimeSlot.find(params[:id])
    end

    private

    def timeslot_params
      params.require(:available_time_slots).permit(:hour, :track_id)
    end
  end

app/controllers/tracks_controller.rb
class TracksController < InheritedResources::Base
  def index
    @tracks = Track.all
    @city_options = Track.all.map { |c| [c.city, c.id] }
    @tracks = Track.where(id: params[:city])
  end

  def new
  end

  def create
    @track = Track.new(track_params)
  end

    def show
      @track = Track.find(params[:id])
    end

  private

    def track_params
      params.require(:tracks).permit(:name, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/available_time_slots_helper.rb
module AvailableTimeSlotsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/available_time_slots/_form.html.erb
<%= form_with(model: available_time_slot, local: true) do |form| %>
  <% if available_time_slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(available_time_slot.errors.count, "error") %> prohibited this available_time_slot from being saved:</h2>

      <ul>
      <% available_time_slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hour %>
    <%= form.datetime_select :hour %>
  </div>

  <div class="field">
    <%= form.label :references %>
    <%= form.text_field :references %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/available_time_slots/edit.html.erb
<h1>Editing Available Time Slot</h1>

<%= render 'form', available_time_slot: @available_time_slot %>

<%= link_to 'Show', @available_time_slot %> |
<%= link_to 'Back', available_time_slots_path %>

app/views/available_time_slots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Available Time Slots</h1>

<table>
  <thead>
    <tr>
      <th>Hour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timeslots.each do |timeslot| %>
      <tr>
        <td><%= timeslot.hour %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Available Time Slot', new_available_time_slot_path %>

app/views/available_time_slots/new.html.erb
<h1>New Available Time Slot</h1>

<%= render 'form', available_time_slot: @available_time_slot %>

<%= link_to 'Back', available_time_slots_path %>

app/views/available_time_slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hour:</strong>
  <%= @available_time_slot.hour %>
</p>

<p>
  <strong>References:</strong>
  <%= @available_time_slot.references %>
</p>

<%= link_to 'Edit', edit_available_time_slot_path(@available_time_slot) %> |
<%= link_to 'Back', available_time_slots_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KartNGo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800|Roboto:400,500,700" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
  </head>
<header>
  <%=  render 'shared/navbar'%>
  <%=  render 'shared/header'%>
  <%= yield %>
</header>
  <body>
    <%=  render 'shared/banner'%>
    <%= yield %>
  </body>
<footer>
  <%=  render 'shared/footer'%>
  <%= yield %>
</footer>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"> </script>

</html>

app/views/shared/_banner.html.erb
<section class="slice-lg sct-color-1" id="sct_full_demos">
    <div class="container">
        <div class="section-title section-title--style-1 text-center mb-3">
            <h3 class="section-title-inner heading-2 strong-600 text-normal">
                <span class="d-block">Réservez votre session en quelques clics !</span>
            </h3>
            <span class="section-title-delimiter clearfix d-none"></span>
        </div>
        <span class="clearfix"></span>
        <div class="fluid-paragraph text-center">
            <div class="text-lg line-height-1_8 c-gray-light strong-300">
							<%= form_tag tracks_path do %>
								<div class="main-search-input">
									<div class="main-search-input-item location ">
										<div id="autocomplete-container">
										 <i class="fa fa-map-marker">  <input type="text" placeholder="Paris" id="autocomplete-input-location" ></i><div><%= select_tag :city, options_for_select(@city_options), prompt: "Choisissez une ville", class: "form-control col-2" %></div>
										</div>
									</div>
								<%= submit_tag("Search", class: "button", onclick: "window.location.href='listings-half-screen-map-list.html' ") %>
								</div>
							<% end %>
						</div>
					</div>
				</div>
        <span class="space-xs-xl"></span>
        <div class="">
            <div class="row">
                                    <div class="col-md-6 startup agency">
                    <div class="block block-image-holder mb-5 image-animate-wrapper">
                        <div class="block-image image-animate--hover">
                            <a href="demos/startup-agency" target="_blank">
                                <img src="assets/images/presentation/demos/startup/agency.jpg" class="rounded">
                            </a>
                        </div>

                        <div class="card-body px-0">
                            <div class="">
                                <a href="html/startup-agency" class="heading heading-4 strong-500" target="_blank">
                                    Startup Agency                                    </a>
                                <p class="c-gray-light mt-2 d-none">
                                    Flexible plugin that utilizes a handful of classes for easy toggle behavior.                                    </p>
                            </div>
                        </div>
                    </div>
                </div>
                                    <div class="col-md-6 startup app">
                    <div class="block block-image-holder mb-5 image-animate-wrapper">
                        <div class="block-image image-animate--hover">
                            <a href="demos/startup-app" target="_blank">
                                <img src="assets/images/presentation/demos/startup/app.jpg" class="rounded">
                            </a>
                        </div>

                        <div class="card-body px-0">
                            <div class="">
                                <a href="html/startup-app" class="heading heading-4 strong-500" target="_blank">
                                    Startup App                                    </a>
                                <p class="c-gray-light mt-2 d-none">
                                    Flexible plugin that utilizes a handful of classes for easy toggle behavior.                                    </p>
                            </div>
                        </div>
                    </div>
                </div>
                                    <div class="col-md-6 startup app">
                    <div class="block block-image-holder mb-5 image-animate-wrapper">
                        <div class="block-image image-animate--hover">
                            <a href="demos/startup-analitycs" target="_blank">
                                <img src="assets/images/presentation/demos/startup/analitycs.jpg" class="rounded">
                            </a>
                        </div>

                        <div class="card-body px-0">
                            <div class="">
                                <a href="html/startup-analitycs" class="heading heading-4 strong-500" target="_blank">
                                    Startup Analitycs                                    </a>
                                <p class="c-gray-light mt-2 d-none">
                                    Flexible plugin that utilizes a handful of classes for easy toggle behavior.                                    </p>
                            </div>
                        </div>
                    </div>
                </div>
                                    <div class="col-md-6 startup classic">
                    <div class="block block-image-holder mb-5 image-animate-wrapper">
                        <div class="block-image image-animate--hover">
                            <a href="demos/startup-classic" target="_blank">
                                <img src="assets/images/presentation/demos/startup/classic.jpg" class="rounded">
                            </a>
                        </div>

                        <div class="card-body px-0">
                            <div class="">
                                <a href="html/startup-classic" class="heading heading-4 strong-500" target="_blank">
                                    Startup Classic                                    </a>
                                <p class="c-gray-light mt-2 d-none">
                                    Flexible plugin that utilizes a handful of classes for easy toggle behavior.                                    </p>
                            </div>
                        </div>
                    </div>
                </div>
                                </div>
        </div>
    </div>
</section>



<!-- Banner
================================================== -->
<div class="main-search-container">
	<div class="main-search-inner">


<!-- script pour l'auto completion
================================================== -->
<script>
	function autocomplete(inp, arr) {
  /*the autocomplete function takes two arguments,
  the text field element and an array of possible autocompleted values:*/
  var currentFocus;
  /*execute a function when someone writes in the text field:*/
  inp.addEventListener("input", function(e) {
      var a, b, i, val = this.value;
      /*close any already open lists of autocompleted values*/
      closeAllLists();
      if (!val) { return false;}
      currentFocus = -1;
      /*create a DIV element that will contain the items (values):*/
      a = document.createElement("DIV");
      a.setAttribute("id", this.id + "autocomplete-list");
      a.setAttribute("class", "autocomplete-items");
      /*append the DIV element as a child of the autocomplete container:*/
      this.parentNode.appendChild(a);
      /*for each item in the array...*/
      for (i = 0; i < arr.length; i++) {
        /*check if the item starts with the same letters as the text field value:*/
        if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
          /*create a DIV element for each matching element:*/
          b = document.createElement("DIV");
          /*make the matching letters bold:*/
          b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
          b.innerHTML += arr[i].substr(val.length);
          /*insert a input field that will hold the current array item's value:*/
          b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
          /*execute a function when someone clicks on the item value (DIV element):*/
          b.addEventListener("click", function(e) {
              /*insert the value for the autocomplete text field:*/
              inp.value = this.getElementsByTagName("input")[0].value;
              /*close the list of autocompleted values,
              (or any other open lists of autocompleted values:*/
              closeAllLists();
          });
          a.appendChild(b);
        }
      }
  });
  /*execute a function presses a key on the keyboard:*/
  inp.addEventListener("keydown", function(e) {
      var x = document.getElementById(this.id + "autocomplete-list");
      if (x) x = x.getElementsByTagName("div");
      if (e.keyCode == 40) {
        /*If the arrow DOWN key is pressed,
        increase the currentFocus variable:*/
        currentFocus++;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 38) { //up
        /*If the arrow UP key is pressed,
        decrease the currentFocus variable:*/
        currentFocus--;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 13) {
        /*If the ENTER key is pressed, prevent the form from being submitted,*/
        e.preventDefault();
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (x) x[currentFocus].click();
        }
      }
  });
  function addActive(x) {
    /*a function to classify an item as "active":*/
    if (!x) return false;
    /*start by removing the "active" class on all items:*/
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = (x.length - 1);
    /*add class "autocomplete-active":*/
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    /*a function to remove the "active" class from all autocomplete items:*/
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
  function closeAllLists(elmnt) {
    /*close all autocomplete lists in the document,
    except the one passed as an argument:*/
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
        x[i].parentNode.removeChild(x[i]);
      }
    }
  }
  /*execute a function when someone clicks in the document:*/
  document.addEventListener("click", function (e) {
      closeAllLists(e.target);
  });
}

/*An array containing all the country names in the world:*/

var ville =['Paris','Cormeilles en Vexin','Wissous','Argenteuil','Nanterre']
/*initiate the autocomplete function on the "myInput" element, and pass along the countries array as possible autocomplete values:*/
autocomplete(document.getElementById("autocomplete-input-location"), ville);
</script>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer id="footer" class="footer ">
<div class="footer-bottom py-4">
    <div class="container">
        <div class="row cols-xs-space col-sm-space align-items-center">
            <div class="col-lg-3 col-12">
                <div class="text-center text-lg-left">
                    <div class="copyright">
                        <ul class="copy-links no-margin">
                            <li>
                                &copy; 2018 Webpixels
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-lg-6">
                <div class="text-center">
                    <ul class="footer-menu footer-menu-sm">
                        <li>
                            <a href="https://webpixels.io" target="_blank" style="padding-left: 0;">Official website</a>
                        </li>
                        <li>
                            <a href="https://instagram.com/webpixels.io" target="_blank" style="padding-left: 0;">Instagram</a>
                        </li>
                        <li>
                            <a href="https://facebook.com/webpixels" target="_blank" style="padding-left: 0;">Facebook</a>
                        </li>
                        <li>
                            <a href="http://support.wrapbootstrap.com/knowledge_base/topics/usage-licenses" target="_blank">License</a>
                        </li>
                        <li>
                            <a href="https://goo.gl/9BbH7R" target="_blank">Buy now</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="text-center text-lg-right">
                    <ul class="social-media social-media--style-1-v4">
                        <li>
                            <a href="https://www.facebook.com/webpixels/" class="facebook" target="_blank" data-toggle="tooltip" data-original-title="Facebook">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/webpixels.io/" class="instagram" target="_blank" data-toggle="tooltip" data-original-title="Instagram">
                                <i class="fa fa-instagram"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://dribbble.com/webpixels" class="dribbble" target="_blank" data-toggle="tooltip" data-original-title="Dribbble">
                                <i class="fa fa-dribbble"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</footer>

app/views/shared/_form.html.erb
<form class="form-horizontal form-global-search z-depth-2-top" role="form">
    <div class="px-4">
        <div class="row">
            <div class="col-12">
                <input type="text" class="search-input" placeholder="Type and hit enter ...">
            </div>
        </div>
    </div>
    <a href="#" class="close-search" data-toggle="global-search" title="Close search bar"></a>
</form>
</div>
</section>

<%= simple_form_for :available_time_slot, url: :available_time_slots, method: :post do |f| %>
<div class="container">
  <div class="row">
    <div class='col-sm-6 col-sm-offset-3'>
      <div class="form-group">
        <div class='input-group date' id='datetimepicker'>
          <%= f.input :hour, label: false, placeholder: "Sélectionnez la date et l'heure", class: "form-control" %>
          <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "C'est parti", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_header.html.erb
<section class="background-image-holder u-py-100 u-h-200vh u-flex-center" data-vide-bg="mp4: assets/videos/kart_video.mp4, data-vide-options="loop: true, muted: true, position: 0% 0%" data-dark-overlay="3">
      <div class="holder-item has-bg-cover bg-size-cover" style="background-position: left center;">
        <span class="mask bg-base-1 alpha-7"></span>
        <div class="overlay">
          <%= video_tag "kart_video.mp4", autoplay: true, loop: true, muted: true %>
          <div class="container slice-lg slice--offset-top">
            <div class="row cols-xs-space align-items-center text-center text-md-left justify-content-center">
                <div class="col-lg-7">
                    <div class="text-center mt-5">
                        <h2 class="heading display-3 font-weight-400 text-white mt-4 mb-0">
                            <span class="font-weight-700">Kart'nGo</span>
                        </h2>
          <h2 class="heading heading-3 font-weight-400 text-white">
                            <span class="font-weight-700">Réservez, Payez, Roulez !</span>
                        </h2>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/tracks/_form.html.erb
<%= form_with(model: track, local: true) do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.name %></td>
        <td><%= track.city %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @track.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @track.city %>
</p>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>